spring:
  thymeleaf:
    cache: false

  security:
    user:
      name: ja
      password: ja

#  datasource:
#    url: jdbc:mysql://localhost:3306/bio?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: ja
#    hikari:
#      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  devtools:
    restart:
      log-condition-evaluation-delta: false


server:
  address: 127.0.0.1
  port: 8001
  error:
    whitelabel:
      enabled: false
debug: true

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

