bio:
  load-database: false
  upload-dir: C:\Projekti\IdeaProjects\bio\misc_local\uploads

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/bio?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ja
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true

  devtools:
    restart:
      log-condition-evaluation-delta: false
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy


server:
  address: 127.0.0.1
  port: 8001
  error:
    whitelabel:
      enabled: false

debug: true

#
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.boot: WARN
#    org.springframework.security: DEBUG


